from python_code.model.tpm_wrapper import TPM


sequence = 'CAAATGCAGCTGGTGCAGTCTGGGCCT...GAGGTGAAGAAGCCTGGGACCTCAGTGAAGGTCTCCTGCAAGGCTTCTGGATTCACCTTT............AC' + \
           'TAGCTCTGCTATGCAGTGGGTGCGACAGGCTCGTGGACAACGCCTTGAGTGGATAGGATGGATCGTCGTTGGC......AGTGGTAACACAAACTACGCACAGAAGTTCCAG..' + \
           '.GAAAGAGTCACCATTACCAGGGACATGTCCACAAGCACAGCCTACATGGAGCTGAGCAGCCTGAGATCCGAGGACACGGCCGTGTATTACTGTGCGGCAGNNNNNNNNNNNNN' +  \
           'NNNNNNNNNCTACGGTATGGACGTCTGGGGCCAAGGGACCACGGTCACCGTCTCCTCA'

model = TPM(params_path='results/model/tpm/vocab_size_100/04_02_2024-21_17_57v_gene_family-all-study-all-v_only-synonymous-no_mmr/state_dict_30000')
probs = model.predict(sequence)
print(probes)
